@extends('layouts.app')

@section('content')
    <div class="container mx-auto px-6 py-10 md:py-10 ">
        <div class="text-center mt-5 mb-10">
            <h5 class="text-4xl md:text-5xl font-extrabold text-gray-900 dark:text-white mb-3">
                Explore Our Course Catalog
            </h5>
            <p class="text-lg text-gray-600 dark:text-gray-400 max-w-3xl mx-auto">
                Discover your next skill from thousands of expertly curated classes and programs.
            </p>
        </div>

        <div class="grid grid-cols-1 lg:grid-cols-4 gap-8">
            <!-- Filter Sidebar -->
            <aside class="lg:col-span-1">
                <!-- Mobile Filter Toggle Button/Header (Visible on screens smaller than large) -->
                <div
                    class="lg:hidden bg-white dark:bg-gray-800 p-4 rounded-xl shadow-lg mb-4 flex justify-between items-center border border-gray-100 dark:border-gray-700">
                    <h3 class="text-lg font-bold text-indigo-600 dark:text-indigo-400 flex items-center">
                        <i data-lucide="filter" class="w-5 h-5 mr-2"></i> Filters
                    </h3>
                    <button id="toggle-filter-btn"
                        class="text-gray-600 dark:text-gray-300 font-semibold px-3 py-1 rounded-lg bg-gray-100 dark:bg-gray-700 flex items-center">
                        <span id="toggle-text">Show</span>
                        <i data-lucide="chevron-down" id="toggle-icon"
                            class="w-4 h-4 ml-2 transition-transform duration-300"></i>
                    </button>
                </div>

                <!-- Filter Content (Collapsible on Mobile, always visible on Desktop) -->
                <div id="filter-content"
                    class="hidden lg:block bg-white dark:bg-gray-800 p-6 rounded-2xl shadow-xl border border-gray-100 dark:border-gray-700 h-fit lg:sticky lg:top-24">

                    <h3 class="hidden lg:flex text-xl font-bold text-indigo-600 dark:text-indigo-400 mb-6 items-center">
                        Filter Courses
                    </h3>

                    <!-- Search Input -->
                    <div class="mb-6">
                        <label for="search-input"
                            class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Search
                            Titles</label>
                        <input type="text" id="search-input" placeholder="e.g., Python, Marketing"
                            class="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-xl bg-gray-50 dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-indigo-500 focus:border-indigo-500 transition duration-200"
                            oninput="applyFilters()">
                    </div>

                    <!-- Category Filter -->
                    <div class="mb-6">
                        <h4 class="text-base font-semibold text-gray-700 dark:text-gray-300 mb-3">Category</h4>
                        <div id="category-filter" class="space-y-2">
                            <!-- Checkboxes generated by JS -->
                        </div>
                    </div>

                    <!-- Difficulty Filter -->
                    <div class="mb-6">
                        <h4 class="text-base font-semibold text-gray-700 dark:text-gray-300 mb-3">Difficulty</h4>
                        <div id="difficulty-filter" class="space-y-2">
                            <!-- Checkboxes generated by JS -->
                        </div>
                    </div>

                    <!-- Reset Button -->
                    <button onclick="resetFilters()"
                        class="w-full bg-gray-200 dark:bg-gray-700 text-gray-700 dark:text-gray-300 font-semibold py-2 rounded-xl hover:bg-gray-300 dark:hover:bg-gray-600 transition duration-300 shadow-md">
                        Clear Filters
                    </button>
                </div>
            </aside>

            <!-- Course List Grid -->
            <section class="lg:col-span-3">
                <div id="course-list" class="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-6">
                    <!-- Course cards rendered here by JavaScript -->
                </div>
                <!-- No results message -->
                <div id="no-results" class="hidden text-center py-20 bg-white dark:bg-gray-800 rounded-2xl shadow-xl mt-6">
                    <i data-lucide="search-x" class="w-12 h-12 text-indigo-500 mx-auto mb-4"></i>
                    <p class="text-xl font-semibold text-gray-700 dark:text-gray-300">
                        No courses found matching your criteria.
                    </p>
                    <button onclick="resetFilters()" class="mt-4 text-indigo-600 dark:text-indigo-400 hover:underline">
                        Reset Filters
                    </button>
                </div>
            </section>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        // Initialize lucide icons
        lucide.createIcons();

        // --- Dummy Course Data ---
        const courses = [{
                id: 1,
                title: "Advanced React & Next.js Development",
                category: "Development",
                difficulty: "Advanced",
                rating: 4.8,
                students: "12,450",
                instructor: "Jane Doe",
                color: "blue"
            },
            {
                id: 2,
                title: "Introduction to Python for Data Science",
                category: "Data Science",
                difficulty: "Beginner",
                rating: 4.5,
                students: "25,100",
                instructor: "John Smith",
                color: "green"
            },
            {
                id: 3,
                title: "Modern CSS & Tailwind UI/UX Design",
                category: "Design",
                difficulty: "Intermediate",
                rating: 4.9,
                students: "9,870",
                instructor: "Emily Ray",
                color: "indigo"
            },
            {
                id: 4,
                title: "Complete Guide to Digital Marketing",
                category: "Business",
                difficulty: "Beginner",
                rating: 4.6,
                students: "45,300",
                instructor: "Michael Chen",
                color: "orange"
            },
            {
                id: 5,
                title: "Cloud Architecture with AWS and Serverless",
                category: "Development",
                difficulty: "Advanced",
                rating: 4.7,
                students: "7,200",
                instructor: "Alex Kim",
                color: "yellow"
            },
            {
                id: 6,
                title: "Machine Learning Fundamentals with Scikit-learn",
                category: "Data Science",
                difficulty: "Intermediate",
                rating: 4.4,
                students: "18,900",
                instructor: "Sarah Lee",
                color: "red"
            },
            {
                id: 7,
                title: "Graphic Design Masterclass: Adobe Illustrator",
                category: "Design",
                difficulty: "Beginner",
                rating: 4.3,
                students: "32,500",
                instructor: "David Lopez",
                color: "pink"
            },
            {
                id: 8,
                title: "Financial Modeling and Valuation Analysis",
                category: "Business",
                difficulty: "Advanced",
                rating: 4.9,
                students: "5,100",
                instructor: "Robert Hall",
                color: "teal"
            },
            {
                id: 9,
                title: "Frontend Performance Optimization",
                category: "Development",
                difficulty: "Intermediate",
                rating: 4.6,
                students: "6,900",
                instructor: "Jessica Oh",
                color: "cyan"
            },
            {
                id: 10,
                title: "Data Visualization with D3.js",
                category: "Data Science",
                difficulty: "Advanced",
                rating: 4.7,
                students: "10,000",
                instructor: "Chris Nolan",
                color: "purple"
            },
        ];

        const courseListContainer = document.getElementById('course-list');
        const noResults = document.getElementById('no-results');

        // --- Dynamic Filter Options ---
        const allCategories = [...new Set(courses.map(c => c.category))];
        const allDifficulties = [...new Set(courses.map(c => c.difficulty))];

        /**
         * Renders a single course card HTML.
         */
        const courseUrl = @json(route('course.details'));

        function createCourseCard(course) {
            const starIcon = `<i data-lucide="star" class="w-4 h-4 text-yellow-400 fill-yellow-400"></i>`;
            const studentIcon = `<i data-lucide="users" class="w-4 h-4 text-gray-400 dark:text-gray-500"></i>`;
            const clockIcon = `<i data-lucide="zap" class="w-4 h-4 text-gray-400 dark:text-gray-500"></i>`;

            const card = document.createElement('div');
            card.className = `
        bg-white dark:bg-gray-800 rounded-2xl p-6 shadow-2xl 
        transition-all duration-300 hover:shadow-indigo-500/20 
        dark:hover:shadow-indigo-700/20 transform hover:-translate-y-1 
        border-t-4 border-${course.color}-500
    `;

            card.innerHTML = `
        <div class="flex justify-between items-start mb-3">
            <span class="text-xs font-semibold px-3 py-1 rounded-full bg-${course.color}-100 text-${course.color}-800 dark:bg-${course.color}-900 dark:text-${course.color}-400">
                ${course.category}
            </span>
            <span class="text-xs font-medium text-gray-500 dark:text-gray-400 flex items-center">
                ${clockIcon} <span class="ml-1">${course.difficulty}</span>
            </span>
        </div>
        <h4 class="text-xl font-bold text-gray-900 dark:text-white mb-2">${course.title}</h4>
        <p class="text-sm text-gray-600 dark:text-gray-400 mb-4">Instructor: ${course.instructor}</p>

        <div class="flex justify-between items-center text-sm pt-4 border-t border-gray-100 dark:border-gray-700">
            <div class="flex items-center space-x-3">
                <span class="flex items-center font-semibold text-gray-700 dark:text-white">
                    ${starIcon} <span class="ml-1">${course.rating}</span>
                </span>
                <span class="flex items-center text-gray-500 dark:text-gray-400">
                    ${studentIcon} <span class="ml-1">${course.students}</span>
                </span>
            </div>
            <button 
                onclick="window.location.href = courseUrl"
                class="text-indigo-600 font-semibold hover:text-indigo-800 transition">
                View Details
            </button>
        </div>
    `;

            // Render Lucide icons inside this card
            lucide.createIcons({
                attr: 'data-lucide',
                parent: card
            });

            return card; // ✅ Return inside the function
        }

        /**
         * Renders all filtered courses to the DOM.
         */
        function renderCourses(filteredCourses) {
            courseListContainer.innerHTML = '';
            if (filteredCourses.length === 0) {
                noResults.classList.remove('hidden');
            } else {
                noResults.classList.add('hidden');
                filteredCourses.forEach(course => {
                    courseListContainer.appendChild(createCourseCard(course));
                });
            }
        }

        /**
         * Applies all active filters and re-renders the course list.
         */
        function applyFilters() {
            const searchInput = document.getElementById('search-input').value.toLowerCase();

            // Get selected categories
            const selectedCategories = Array.from(document.querySelectorAll('#category-filter input:checked'))
                .map(input => input.value);

            // Get selected difficulties
            const selectedDifficulties = Array.from(document.querySelectorAll('#difficulty-filter input:checked'))
                .map(input => input.value);

            let filtered = courses.filter(course => {
                // 1. Title Search
                const matchesSearch = course.title.toLowerCase().includes(searchInput);

                // 2. Category Filter
                const matchesCategory = selectedCategories.length === 0 || selectedCategories.includes(course
                    .category);

                // 3. Difficulty Filter
                const matchesDifficulty = selectedDifficulties.length === 0 || selectedDifficulties.includes(course
                    .difficulty);

                return matchesSearch && matchesCategory && matchesDifficulty;
            });

            renderCourses(filtered);
        }

        /**
         * Generates the filter checkboxes dynamically.
         */
        function setupFilters() {
            const categoryFilterDiv = document.getElementById('category-filter');
            const difficultyFilterDiv = document.getElementById('difficulty-filter');

            // Category Checkboxes
            allCategories.forEach(category => {
                categoryFilterDiv.innerHTML += `
                    <label class="flex items-center text-gray-600 dark:text-gray-400 text-sm cursor-pointer hover:text-indigo-600 dark:hover:text-indigo-400 transition duration-150">
                        <input type="checkbox" value="${category}" onchange="applyFilters()"
                            class="h-4 w-4 text-indigo-600 border-gray-300 dark:border-gray-600 dark:bg-gray-700 rounded focus:ring-indigo-500 mr-2">
                        ${category}
                    </label>
                `;
            });

            // Difficulty Checkboxes
            allDifficulties.forEach(difficulty => {
                difficultyFilterDiv.innerHTML += `
                    <label class="flex items-center text-gray-600 dark:text-gray-400 text-sm cursor-pointer hover:text-indigo-600 dark:hover:text-indigo-400 transition duration-150">
                        <input type="checkbox" value="${difficulty}" onchange="applyFilters()"
                            class="h-4 w-4 text-indigo-600 border-gray-300 dark:border-gray-600 dark:bg-gray-700 rounded focus:ring-indigo-500 mr-2">
                        ${difficulty}
                    </label>
                `;
            });
        }

        /**
         * Resets all filter inputs and re-renders.
         */
        function resetFilters() {
            document.getElementById('search-input').value = '';
            document.querySelectorAll('#category-filter input, #difficulty-filter input').forEach(input => {
                input.checked = false;
            });
            applyFilters();
        }

        // --- Filter Collapse Logic ---
        const toggleFilterBtn = document.getElementById('toggle-filter-btn');
        const filterContent = document.getElementById('filter-content');
        const toggleIcon = document.getElementById('toggle-icon');
        const toggleText = document.getElementById('toggle-text');

        if (toggleFilterBtn) {
            toggleFilterBtn.addEventListener('click', () => {
                filterContent.classList.toggle('hidden');

                const isHidden = filterContent.classList.contains('hidden');

                if (isHidden) {
                    toggleIcon.classList.remove('rotate-180');
                    toggleText.textContent = 'Show';
                } else {
                    toggleIcon.classList.add('rotate-180');
                    toggleText.textContent = 'Hide';
                }

                // Re-create lucide icons inside the newly visible content
                if (!isHidden) {
                    lucide.createIcons({
                        attr: 'data-lucide',
                        parent: filterContent
                    });
                }
            });
        }


        // --- Modal Logic (Kept for continuity) ---

        const loginModal = document.getElementById('loginModal');
        const loginContent = document.getElementById('loginContent');
        const signupModal = document.getElementById('signupModal');
        const signupContent = document.getElementById('signupContent');

        const openLoginBtnHeader = document.getElementById('openLoginModalBtn');
        const openSignupBtnHeader = document.getElementById('openSignupModalBtn');
        const openLoginBtnMain = document.getElementById('openLoginBtnMain');

        const closeLoginModalBtn = document.getElementById('closeLoginModal');
        const closeSignupModalBtn = document.getElementById('closeSignupModal');

        const switchToSignupLink = document.getElementById('switchToSignup');
        const switchToLoginLink = document.getElementById('switchToLogin');

        function openModal(modal, content) {
            modal.classList.add('show-modal');
            setTimeout(() => {
                modal.classList.remove('opacity-0');
                modal.classList.add('opacity-100');
                content.classList.remove('scale-90', 'opacity-0');
                content.classList.add('scale-100', 'opacity-100');
            }, 10);
        }

        function closeModal(modal, content) {
            modal.classList.remove('opacity-100');
            modal.classList.add('opacity-0');
            content.classList.remove('scale-100', 'opacity-100');
            content.classList.add('scale-90', 'opacity-0');
            setTimeout(() => {
                modal.classList.remove('show-modal');
            }, 300);
        }

        function switchModal(currentModal, currentContent, targetModal, targetContent) {
            currentContent.classList.remove('scale-100', 'opacity-100');
            currentContent.classList.add('scale-90', 'opacity-0');
            setTimeout(() => {
                currentModal.classList.remove('show-modal', 'opacity-100');
                currentModal.classList.add('opacity-0');
                targetModal.classList.add('show-modal');
                openModal(targetModal, targetContent);
            }, 280);
        }

        if (openLoginBtnHeader) openLoginBtnHeader.addEventListener('click', (e) => {
            e.preventDefault();
            closeModal(signupModal, signupContent);
            openModal(loginModal, loginContent);
        });
        if (openLoginBtnMain) openLoginBtnMain.addEventListener('click', (e) => {
            e.preventDefault();
            openModal(loginModal, loginContent);
        });
        if (openSignupBtnHeader) openSignupBtnHeader.addEventListener('click', (e) => {
            e.preventDefault();
            closeModal(loginModal, loginContent);
            openModal(signupModal, signupContent);
        });
        if (closeLoginModalBtn) closeLoginModalBtn.addEventListener('click', () => {
            closeModal(loginModal, loginContent);
        });
        if (closeSignupModalBtn) closeSignupModalBtn.addEventListener('click', () => {
            closeModal(signupModal, signupContent);
        });

        loginModal.addEventListener('click', (e) => {
            if (e.target === loginModal) closeModal(loginModal, loginContent);
        });
        signupModal.addEventListener('click', (e) => {
            if (e.target === signupModal) closeModal(signupModal, signupContent);
        });

        if (switchToSignupLink) switchToSignupLink.addEventListener('click', (e) => {
            e.preventDefault();
            switchModal(loginModal, loginContent, signupModal, signupContent);
        });

        if (switchToLoginLink) switchToLoginLink.addEventListener('click', (e) => {
            e.preventDefault();
            switchModal(signupModal, signupContent, loginModal, loginContent);
        });

        document.querySelector('#loginModal form').addEventListener('submit', (e) => {
            e.preventDefault();
            console.log('Login attempt captured: Form submitted.');
            closeModal(loginModal, loginContent);
        });
        document.querySelector('#signupModal form').addEventListener('submit', (e) => {
            e.preventDefault();
            console.log('Sign Up attempt captured: Form submitted.');
            closeModal(signupModal, signupContent);
        });

        // --- Initialization ---
        window.onload = () => {
            setupFilters();
            applyFilters();
        };
    </script>
@endpush
